name: MR Checks
on: [ pull_request ]

jobs:
  e2e-demo:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup vx
        uses: loonghao/vx@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          setup: 'true'
      - name: Run demo workflow and demo script
        run: |
          vx just run-demo

  python-check:

    strategy:
      max-parallel: 4
      matrix:
        target:
          - os: 'ubuntu-22.04'
            triple: 'x86_64-unknown-linux-gnu'
          - os: 'macos-13'
            triple: 'x86_64-apple-darwin'
          - os: 'windows-2022'
            triple: 'x86_64-pc-windows-msvc'
      fail-fast: false
    runs-on: ${{ matrix.target.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup vx
        uses: loonghao/vx@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          setup: 'true'
      - name: lint
        run: |
          vx uvx nox -s lint

